FROM mysql:8.0

# ENV MYSQL_DATABASE=lems
# ENV MYSQL_USER=lems
# ENV MYSQL_PASSWORD=lems
# ENV MYSQL_ROOT_PASSWORD=root

EXPOSE 3306

CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
